(() => {
  'use strict';
  if('scrollRestoration' in history)history.scrollRestoration='manual';
  const content=window.PORTFOLIO;
  const $=s=>document.querySelector(s);
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const read=k=>{try{return localStorage.getItem(k)}catch{return null}};
  const save=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
  const motion=window.portfolioMotion;
  let lang='en',t,s,currentRoute='intro',cleanup=null,lastURL='',visibleSection='intro';
  const href=route=>`?lang=${lang}#${route}`;
  const cv=()=>`cv/Ioannis-Koupidis-CV-${lang}.pdf${lang==='el'?'?v=greek-copy-2':''}`;
  const meta=(n,label)=>`<span class="section-label"><span class="label-cross" aria-hidden="true">+</span>${n} / ${esc(label)}</span>`;
  const list=points=>`<ul class="evidence-list">${points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul>`;
  const heading=words=>`${esc(words[0])}<br><em>${esc(words[1])}</em>`;
  function cover(p){
    if(p.id==='scribe')return `<div class="work-art scribe-art"><div class="art-orbit" aria-hidden="true"></div><span class="art-word" aria-hidden="true">Scribe</span><img class="scribe-window" src="assets/images/scribe/recording.png" alt="${esc(p.chapters[2].caption)}" width="1440" height="960" loading="lazy"><span class="art-badge">macOS / 2026</span></div>`;
    if(p.id==='agent-x')return `<div class="work-art agent-art"><span class="agent-id" aria-hidden="true">AX / 01</span><div class="agent-crosshair" aria-hidden="true"><i></i><i></i></div><div class="agent-grid" aria-hidden="true"></div><span class="agent-title" aria-hidden="true">AGENT<br><b>X</b></span><span class="art-badge">${esc(p.tag)} / 2026</span></div>`;
    if(p.id==='radio')return `<div class="work-art radio-art"><span class="radio-word" aria-hidden="true">On air.</span><div class="radio-disc" aria-hidden="true"></div><img class="radio-phone phone-one" src="assets/images/radio/browse.png" alt="${esc(p.chapters[0].caption)}" width="390" height="844" loading="lazy"><img class="radio-phone phone-two" src="assets/images/radio/player.png" alt="${esc(p.chapters[2].caption)}" width="390" height="844" loading="lazy"><span class="art-badge">iOS / 2026</span></div>`;
    return `<div class="work-art future-art"><span class="future-orbit" aria-hidden="true"></span>${p.cover?`<img src="assets/images/${esc(p.cover)}" alt="${esc(p.name)}" loading="lazy">`:`<span class="future-name">${esc(p.name)}</span>`}<span class="art-badge">${esc(p.tag)}</span></div>`;
  }
  function workCard(p,i){return `<article class="work-piece piece-${p.id}" data-reveal><a class="work-link" href="${href(`work/${p.id}`)}" aria-label="${esc(s.caseAction)}: ${esc(p.name)}">${cover(p)}<div class="work-caption"><h3>${esc(p.name)}<span aria-hidden="true">↗</span></h3><span>${esc(p.kind)}</span></div></a><div class="work-detail"><p>${esc(p.description)}</p><span class="work-status"><i aria-hidden="true"></i>${esc(p.status)}</span></div></article>`}
  function home(){
    return `<div class="home-page">
      <section class="hero" id="intro" data-section="intro">
        <div class="hero-top"><p class="hero-role"><span class="hero-name">Ioannis Koupidis</span>${esc(s.heroLabel[0])}<br>${esc(s.heroLabel[1])}</p><p class="hero-code">${esc(s.heroCode)}</p><p class="hero-current">${esc(s.heroCurrent)}</p></div>
        <div class="hero-art" data-glass="hero" aria-hidden="true"><div class="hero-glow"></div><img src="assets/ribbon.png" width="1536" height="1024" fetchpriority="high" alt=""></div>
        <div class="hero-title"><h1><span>${esc(s.heroTitle[0])}</span><span>${esc(s.heroTitle[1])} <em>${esc(s.heroTitle[2])}</em></span></h1></div>
        <div class="hero-bottom"><div class="hero-bottom-actions"><a class="scroll-cue" href="${href('perspective')}"><span class="round-arrow" aria-hidden="true">↓</span>${esc(s.scroll)}</a><a class="hero-cv" href="${cv()}" download>${esc(s.viewCV)} ↓</a></div><p>${esc(s.heroIntro)}</p></div>
        <span class="hero-corner corner-a" aria-hidden="true">+</span><span class="hero-corner corner-b" aria-hidden="true">+</span>
      </section>
      <section class="perspective section-space" id="perspective" data-section="perspective">
        <div class="perspective-aside">${meta('01',s.pointLabel)}<div class="number-print" aria-hidden="true"><span>13</span><span>13</span></div><p>${esc(s.pointSmall)}</p></div>
        <div class="perspective-copy"><p class="reading-statement" data-reading>${s.point.split(' ').map(w=>`<span>${esc(w)} </span>`).join('')}</p><a class="text-link" href="${href('experience')}">${esc(s.experienceMore)} <span aria-hidden="true">↗</span></a></div>
      </section>
      <section class="work section-space" id="work" data-section="work"><div class="section-header">${meta('02',s.workLabel)}<h2>${heading(s.workHeadline)}</h2><span class="section-count">(0${t.projects.length})</span></div><div class="work-gallery">${t.projects.map(workCard).join('')}</div><p class="gallery-note">${esc(t.workNote)}</p></section>
      <section class="signal-sequence" id="approach" data-section="approach"><div class="signal-scene"><canvas id="signal-canvas" aria-hidden="true"></canvas><div class="signal-heading"><span class="signal-kicker">${esc(t.approach)}</span><h2>${s.filmWords.map(w=>`<span>${esc(w)}</span>`).join('')}</h2><p>${esc(s.filmNote)}</p></div><span class="signal-coordinate" aria-hidden="true">[ 01 → 03 ]</span></div></section>
      <section class="experience section-space" id="experience" data-section="experience"><div class="section-header">${meta('03',s.experienceLabel)}<h2>${heading(s.experienceHeadline)}</h2></div><div class="experience-opening"><span class="experience-years">13<span>${esc(t.years)}</span></span><p>${esc(t.experienceIntro)}</p></div><div class="company-list">${t.companies.map((c,i)=>`<article class="company" data-reveal><div class="company-title"><span class="section-label">0${i+1} / ${esc(c.dates)}</span><h3>${esc(c.name)}</h3><span>${esc(c.role)}</span></div><div class="company-body"><h4>${esc(c.title)}</h4><p>${esc(c.body)}</p>${list(c.points)}${i===0?`<div class="company-metrics">${c.metrics.map(([v,l])=>`<div><strong>${esc(v)}</strong><span>${esc(l)}</span></div>`).join('')}</div>`:''}<p class="fine-print">${esc(c.note)}</p></div></article>`).join('')}</div></section>
      <section class="about section-space" id="about" data-section="about"><div class="about-heading">${meta('04',s.aboutLabel)}<h2>${heading(t.aboutTitle)}</h2><p>${esc(t.aboutIntro)}</p></div><div class="profile-grid"><section><h3>${esc(t.education)}</h3>${t.educationItems.map(([n,school,date])=>`<div class="education-row"><span class="year">${esc(date)}</span><strong>${esc(n)}</strong><span>${esc(school)}</span></div>`).join('')}</section><section><h3>${esc(t.skills)}</h3>${list(t.skillItems)}</section><section class="earlier"><h3>${esc(t.earlier)}</h3>${t.earlierItems.map(([c,r,d])=>`<div><strong>${esc(c)}</strong><span>${esc(r)}</span><time>${esc(d)}</time></div>`).join('')}</section></div><div class="language-facts"><span class="section-label">${esc(t.languagesTitle)}</span>${t.languageItems.map(([n,l])=>`<span><strong>${esc(n)}</strong>${esc(l)}</span>`).join('')}</div></section>
      ${contact()}
    </div>`;
  }
  function contact(){return `<section class="contact" id="contact" data-section="contact"><div class="contact-top">${meta('05',t.nav[4])}<a class="text-link" href="${cv()}" download>${esc(s.viewCV)} ↓</a></div><div class="contact-art" data-glass="contact" aria-hidden="true"><img src="assets/ribbon.png" width="1536" height="1024" alt="" loading="lazy"></div><div class="contact-main"><h2>${heading(s.contactHeadline)}</h2><a class="contact-cta" href="mailto:gkoupidis@gmail.com">${esc(s.contactLink)}<span aria-hidden="true">↗</span></a></div><div class="contact-end"><div><a href="mailto:gkoupidis@gmail.com">gkoupidis@gmail.com</a><a href="tel:+46739558253">+46 (0) 73 955 82 53</a></div><div><a href="https://www.linkedin.com/in/koupidisyannis/" target="_blank" rel="noopener">LinkedIn ↗</a><a href="https://github.com/IoannisKP" target="_blank" rel="noopener">GitHub ↗</a></div><a class="back-top" href="${href('intro')}">${esc(s.backTop)} ↑</a></div></section>`}
  function caseStudy(id){
    const p=t.projects.find(p=>p.id===id);if(!p)return `<section class="missing"><h1>${esc(t.notFound)}</h1><a href="${href('work')}">${esc(t.back)} ↗</a></section>`;
    const next=t.projects[(t.projects.indexOf(p)+1)%t.projects.length];
    return `<article class="case-page"><header class="case-opening" id="case-intro" data-section="case-intro"><a class="text-link" href="${href('work')}">← ${esc(t.back)}</a><span class="section-label">${esc(p.kind)}</span><h1>${esc(p.name)}<sup>0${t.projects.indexOf(p)+1}</sup></h1><p>${esc(p.description)}</p><div class="case-facts"><div><span>${esc(t.role)}</span><strong>${esc(p.role)}</strong></div><div><span>${esc(t.duration)}</span><strong>${esc(p.duration)}</strong></div><div><span>${esc(t.status)}</span><strong>${esc(p.status)}</strong></div></div></header><div class="case-hero-art">${cover(p)}</div><nav class="case-nav" aria-label="${esc(t.chapter)}">${p.chapters.map((c,i)=>`<a href="${href(`work/${id}/${i}`)}"><span>0${i+1}</span>${esc(c.label)}</a>`).join('')}</nav><div class="case-sections">${p.chapters.map((c,i)=>`<section class="case-section" id="chapter-${i}" data-chapter="${i}"><div class="case-aside">${meta('0'+(i+1),c.label)}<div class="case-signal"><strong>${esc(c.signal[0])}</strong><span>${esc(c.signal[1])}</span></div></div><div class="case-content"><h2>${esc(c.title)}</h2><p class="case-lead">${esc(c.body)}</p>${list(c.points)}${c.image?`<figure class="case-media ${id==='radio'?'phone-media':''}"><a href="assets/images/${c.image}" target="_blank" rel="noopener" aria-label="${esc(t.openImage)}"><img src="assets/images/${c.image}" alt="${esc(c.caption)}" width="${c.imageWidth||(id==='radio'?1206:2440)}" height="${c.imageHeight||(id==='radio'?2622:1514)}" loading="lazy"></a><figcaption>${esc(c.caption)}</figcaption></figure>`:`<div class="research-evidence"><div class="research-sequence" aria-hidden="true">${i===0?'<span>01</span><i>→</i><span>08</span>':i===2?'<span>3 / 3</span><i>≠</i><span>✓</span>':'<span>?</span><i>→</i><span>↗</span>'}</div><p>${esc(c.caption)}</p></div>`}</div></section>`).join('')}</div><div class="case-end"><a href="${esc(p.repo)}" target="_blank" rel="noopener" class="text-link">${esc(t.source)} ↗</a><span>${esc(p.status)}</span></div><a class="next-case" href="${href(`work/${next.id}`)}"><span class="section-label">${esc(s.keepExploring)}</span><span>${esc(next.name)}<i aria-hidden="true">↗</i></span></a></article>`;
  }
  function syncLanguageLinks(route){$('.languages').innerHTML=Object.keys(content).map(c=>`<a href="?lang=${c}#${route}" lang="${c}" hreflang="${c}" ${lang===c?'aria-current="true"':''}>${c.toUpperCase()}</a>`).join('')}
  function chrome(){
    document.documentElement.lang=lang;document.title=`Ioannis Koupidis · ${currentRoute.startsWith('work/')?(t.projects.find(p=>p.id===currentRoute.split('/')[1])?.name||t.edition):t.edition}`;$('meta[name="description"]').content=t.cvSummary;
    $('.identity').href=href('intro');$('.identity').setAttribute('aria-label',`Ioannis Koupidis, ${t.nav[0]}`);$('.skip').textContent=t.skip;
    $('#navigation').setAttribute('aria-label',t.mainNav);$('#navigation').innerHTML=[['work',t.nav[1]],['experience',t.nav[2]],['about',t.nav[3]],['contact',t.nav[4]]].map(([r,l])=>`<a href="${href(r)}">${esc(l)}</a>`).join('');
    $('.languages').setAttribute('aria-label',t.language);syncLanguageLinks(currentRoute);
    $('#theme-label').textContent=t.theme[0];[...$('#theme').options].forEach((o,i)=>o.textContent=t.theme[i+1]);$('#footer-left').textContent=t.location;updateMotion();clock();
  }
  function updateMotion(){const off=motion.isOff();$('#motion-control').textContent=off?s.motionOff:s.motionOn;$('#motion-control').setAttribute('aria-pressed',String(!off));}
  function clock(){if(t)$('#stockholm-time').textContent=new Intl.DateTimeFormat(lang,{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Europe/Stockholm'}).format(new Date())}
  function isCase(route){return route.startsWith('work/')}
  function sectionChanged(id){visibleSection=id;document.querySelectorAll('#navigation a').forEach(a=>{const active=a.hash.slice(1)===id||(id==='perspective'&&a.hash==='#about')||(isCase(currentRoute)&&a.hash==='#work');if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')});if(isCase(currentRoute)&&id.startsWith('chapter-')){currentRoute=`work/${currentRoute.split('/')[1]}/${id.slice(8)}`;syncLanguageLinks(currentRoute)}else if(isCase(currentRoute)&&id==='case-intro'){currentRoute=`work/${currentRoute.split('/')[1]}`;syncLanguageLinks(currentRoute)}else if(!isCase(currentRoute))syncLanguageLinks(id)}
  function goTo(route,behavior='auto',focus=false){let target;if(isCase(route)){const chapter=route.split('/')[2];target=chapter!==undefined?$(`#chapter-${Number(chapter)}`):$('.case-opening')}else target=document.getElementById(route)||$('#intro');if(!target)return;target.scrollIntoView({behavior,block:'start'});if(focus){const h=target.querySelector('h1,h2')||target;h.setAttribute('tabindex','-1');h.focus({preventScroll:true})}}
  function render(route,language){if(cleanup)cleanup();currentRoute=route;lang=Object.hasOwn(content,language)?language:'en';t=content[lang];s=t.story;chrome();$('#main').innerHTML=isCase(route)?caseStudy(route.split('/')[1]):home();document.body.classList.toggle('reading-case',isCase(route));cleanup=window.initPortfolioExperience({onSection:sectionChanged});lastURL=location.href}
  function navigate(url,restore=false){
    const nextURL=new URL(url,location.href);const nextLang=nextURL.searchParams.get('lang')||lang;const route=nextURL.hash.slice(1)||'intro';const languageChange=nextLang!==lang;const samePage=!languageChange&&((!isCase(route)&&!isCase(currentRoute))||(isCase(route)&&isCase(currentRoute)&&route.split('/')[1]===currentRoute.split('/')[1]));
    if(!restore)history.pushState({},'',nextURL.href);
    if(samePage){currentRoute=route;goTo(route,motion.isOff()?'auto':'smooth',true);syncLanguageLinks(route)}else{
      let offset=0;if(languageChange){const id=isCase(currentRoute)?(currentRoute.split('/')[2]!==undefined?`chapter-${currentRoute.split('/')[2]}`:'case-intro'):visibleSection;const old=document.getElementById(id);if(old)offset=Math.max(0,-old.getBoundingClientRect().top/old.offsetHeight)}
      const apply=()=>{render(route,nextLang);goTo(route,'auto',!languageChange);if(offset){const id=isCase(route)?(route.split('/')[2]!==undefined?`chapter-${route.split('/')[2]}`:'case-intro'):route;const el=document.getElementById(id);if(el)window.scrollBy(0,offset*el.offsetHeight)}};
      if(document.startViewTransition&&!motion.isOff())document.startViewTransition(apply).finished.catch(()=>{});else apply();
    }
    save('riso-language',nextLang);lastURL=location.href;
  }
  document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a||e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||a.target||a.hasAttribute('download'))return;const u=new URL(a.href,location.href);if(u.origin===location.origin&&u.pathname===location.pathname&&u.hash&&u.hash!=='#main'){e.preventDefault();navigate(u.href)}});
  const restore=()=>{if(location.href!==lastURL)navigate(location.href,true)};addEventListener('popstate',restore);addEventListener('hashchange',restore);
  const stored=read('riso-theme');$('#theme').value=['system','light','dark'].includes(stored)?stored:'system';$('#theme').addEventListener('change',e=>{document.documentElement.dataset.theme=e.target.value;save('riso-theme',e.target.value)});
  $('#motion-control').addEventListener('click',()=>motion.toggle());addEventListener('portfolio-motion',updateMotion);
  const initialLang=new URLSearchParams(location.search).get('lang')||read('riso-language')||'en';render(location.hash.slice(1)||'intro',initialLang);if(location.hash)requestAnimationFrame(()=>goTo(currentRoute));setInterval(clock,30000);
})();
